### PR TITLE
Completely rebase strings.xml for PT-BR and fully translate

### PR DESCRIPTION
**Pull request by ghost**
Fixed derps, added new lines, aligned code (I hope!)

### CODE REVIEW

**Comment by ghost** [comment]
@BigBrother1984 As you asked me, there it is. New lines, code aligned, derps fixed. All yours to merge. :D

**Comment by kaluoshi** [comment]
@gafanhotz Merging but you missed something. i'll comment them in the commit's lines.

**Comment by ghost** [comment]
@BigBrother1984  Can you point me later (or mail me pedrogafanhoto at gmail.com) what I've lost? It's a bit hard to me to find the comments on lines and more lines on the commit.

Also, I'll mention you on two more commits I've sent to see if they're ready too.

**Comment by kaluoshi** [comment]
@gafanhotz i mentioned you in the comments, check your emails

**Pull request merged**
