### PR TITLE
Create pa_strings.xml

### PR DESCRIPTION
**Pull request by TomasValenta**
czech translation

### CODE REVIEW

**Comment by Anu6is** [comment]
Would you be able to submit these to gerrit. We aren't merging pull requests directly through git hub. 
Thanks

**Comment by TomasValenta** [comment]
yop

**Comment by TomasValenta** [comment]
Please, tell me, how to send to your gerrit? i tried create local clone with git (after registering account), add file, commit and push, but unsuccessfully...

**Comment by Anu6is** [comment]
Try this guide - http://forum.xda-developers.com/showthread.php?t=2484177

**Comment by Anu6is** [comment]
Sorry, as I was initially responding to this via email I did not notice which repo this was. 
You should actually be translating from and submitting to 
https://github.com/AOSPA

This ParanoidAndroid repo is no longer used. Sorry about that

**Comment by TomasValenta** [comment]
Ok, thank you. I use now AOSPA, github suits me more  ;)

**Pull request closed without merging**
