### PR TITLE
Polish Translations FINISHED

### PR DESCRIPTION
**Pull request by pawlo999**
It's COMLETE translation of all ParanoidAndroid stuff

### CODE REVIEW

**Comment by veteran29** [comment]
I translated more, im leaving everythig past " " for ya :)

**Comment by SferaDev** [comment]
It's finished? I don't find any pull request of Veteran29. @veteran29 could you add your strings to the fork of @pawlo999 It will be better to have it on one pull request. Also I'm facing with some untranslated strings on hardware keys it's WIP?

**Comment by veteran29** [comment]
how can i add pull request to his fork? do i need to fork his fork? :D

**Comment by pawlo999** [comment]
I don't really know if you have or not, anyway @veteran29 i'm waiting for your request to finish translation.

**Pull request closed without merging**
